services:

  xpense:
    image: jljl1337/xpense:latest
    container_name: vps-xpense
    restart: unless-stopped
    volumes:
      - ${SHARED_DATA}/xpense:/xpense/data
    environment:
      - TZ=${TZ}
      - SQLITE_BACKUP_CRON_SCHEDULE=0 * * * *